name: Matterbridge Home Assistant Application (Test)
version: 2026.2.4
slug: matterbridge-test
description: Matterbridge Home Assistant Application (Test)
url: "https://github.com/Luligu/matterbridge-home-assistant-addon-test"
changelog: "https://github.com/Luligu/matterbridge-home-assistant-addon-test/blob/main/CHANGELOG.md"

arch:
  - amd64
  - aarch64

image: luligu/matterbridge

panel_title: Matterbridge (Test)
panel_icon: mdi:bridge

ingress: true
ingress_port: 8283

map:
  - addons:rw

host_network: true
startup: services
init: false

schema:
  frontend_bind: str
  branch: list(main|dev)
  force_update: bool

options:
  frontend_bind: 0.0.0.0
  branch: main
  force_update: true
